[book]
authors = ["matthewacon"]
language = "en"
multilingual = false
src = "src"
title = "CX Documentation"

[output.katex]

[preprocessor.katex]
static-css = true
trust = true

[output.html]
preferred-dark-theme = "ayu"
default-theme = "ayu"
git-repository-url = "https://github.com/matthewacon/CX"
edit-url-template = "https://github.com/matthewacon/CX/edit/main/docs/{path}"

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = true
copyable = true
line-numbers = true

[output.linkcheck]
follow-web-links = false
traverse-parent-directories = false
